# dockerfile build demo example
#   ansible-playbook -vv main.yaml
# rebuild existing app from source only
#   ansible-playbook -vv main.yaml --tags 'build'
#
---
- hosts: localhost
  vars:
    ocp_user: developer
    ocp_pwd: developer
    ocp_server: 192.168.137.2:8443
    ocp_project: samplepipeline
    ocp_app: jenkins-pipeline-example
    ocp_dname: "Pipeline Sample"
    ocp_desc: "Pipeline Sample"
  tasks:
    - name: touch a file in tmp
      shell: touch /tmp/run_from_cloudforms
      ignore_errors: yes
      register: touch_tmp
      
    - name: check openshift log in
      shell: oc whoami
      ignore_errors: yes
      register: oc_whoami
      
    - name: login to openshift
      shell: "oc login -u {{ocp_user}} -p {{ocp_pwd}} --server=https://{{ocp_server}} --insecure-skip-tls-verify=true"
      tags: build
      when: ocp_user not in oc_whoami.stdout
      
    - name: create openshift project "{{ocp_project}}"
      shell: "oc new-project {{ocp_project}} --display-name=\"{{ocp_dname}}\" --description=\"{{ocp_desc}}\""
      register: command_result
      failed_when: "command_result.rc != 0 and 'AlreadyExists' not in command_result.stderr"

    - name: create openshift application
      #shell: "oc new-app jenkins-pipeline-example"
      shell: "oc new-app {{ocp_app}}"
      register: command_result
      failed_when: "command_result.rc != 0 and 'already exists' not in command_result.stderr"
      
    - name: start pipeline build
      shell: "oc start-build sample-pipeline"
      register: command_result        
